name: finnhub_project
description: "Finnhub"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_local_notifications: ^17.1.2
  flutter_riverpod: ^2.4.9
  flutter_web_auth_2: ^3.1.2
  google_sign_in: ^6.2.1
  http: ^1.2.1
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  web_socket_channel: ^2.4.5
  flutter_native_splash: ^2.3.10
  icons_launcher: ^2.1.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

  json_serializable: ^6.7.1

  riverpod_generator: ^2.3.5

icons_launcher:
  image_path: "assets/images/icon.png"
  adaptive_background_color: '#222222'
  platforms:
    android:
      enable: true
    ios:
      enable: true



flutter_native_splash:
  color: "#222222"
  image: "assets/images/splash.jpg"
  android_12:
    image: "assets/images/splash.jpg"
    color: "#222222"

    

flutter:


  uses-material-design: true
 
  assets:
    - assets/images/
    
