// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOa-vxgV9wu7gpTGoNt-rELYTEZSLQkcU',
    appId: '1:957951261557:web:7d6209b62f6b5330c6f13c',
    messagingSenderId: '957951261557',
    projectId: 'finnhubtracker',
    authDomain: 'finnhubtracker.firebaseapp.com',
    storageBucket: 'finnhubtracker.appspot.com',
    measurementId: 'G-QWE0LPMNX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDppkAtTJZ0WR7JQ9hzMHBF4152US8x3Ok',
    appId: '1:957951261557:android:f561cd4bc3929773c6f13c',
    messagingSenderId: '957951261557',
    projectId: 'finnhubtracker',
    storageBucket: 'finnhubtracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAygSY7WBkQ1QunbB68E9GSJ0Tom63e1f4',
    appId: '1:957951261557:ios:c5b5e737d96bcbc3c6f13c',
    messagingSenderId: '957951261557',
    projectId: 'finnhubtracker',
    storageBucket: 'finnhubtracker.appspot.com',
    iosClientId: '957951261557-l6oej2t7kduc1qmajgs2kettomq8dil2.apps.googleusercontent.com',
    iosBundleId: 'com.example.finnhubProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAygSY7WBkQ1QunbB68E9GSJ0Tom63e1f4',
    appId: '1:957951261557:ios:c5b5e737d96bcbc3c6f13c',
    messagingSenderId: '957951261557',
    projectId: 'finnhubtracker',
    storageBucket: 'finnhubtracker.appspot.com',
    iosClientId: '957951261557-l6oej2t7kduc1qmajgs2kettomq8dil2.apps.googleusercontent.com',
    iosBundleId: 'com.example.finnhubProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOa-vxgV9wu7gpTGoNt-rELYTEZSLQkcU',
    appId: '1:957951261557:web:dc502bb11e7dbdc6c6f13c',
    messagingSenderId: '957951261557',
    projectId: 'finnhubtracker',
    authDomain: 'finnhubtracker.firebaseapp.com',
    storageBucket: 'finnhubtracker.appspot.com',
    measurementId: 'G-DLWD19VJZ2',
  );
}
